
services:
  - type: web
    name: civicpulse
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn civicpulse.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: civicpulse.settings
