# Generated by Django 5.2.3 on 2025-06-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicpulse', '0002_issue_image_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=50),
        ),
    ]
