# Generated by Django 5.2.2 on 2025-06-21 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicpulse', '0004_issue_latitude_issue_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='issue_images/')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='civicpulse.issue')),
            ],
        ),
    ]
