# Generated by Django 5.2.2 on 2025-06-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicpulse', '0008_alter_comment_options_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
